services:
  mempool:
    build:
      dockerfile: ./cmd/mempool/Dockerfile
      context: .
    ports:
      - "8181:8181"
    volumes:
      - ./data:/data
    develop:
      watch:
        - action: rebuild
          path: ./cmd/mempool
          target: ./app
          ignore:
            - .git/
            - .gitignore
            - README.md
        - action: rebuild
          path: ./internal
          target: ./app
        - action: rebuild
          path: ./proto
          target: ./app
