services:
  mempool:
    build:
      dockerfile: ./cmd/mempool/Dockerfile
      context: .
    ports:
      - "8181:8181"
    environment:
      - API_PORT=8181
    volumes:
      - ./data:/data
    develop:
      watch:
        - action: rebuild
          path: ./cmd/mempool
          target: ./app
          ignore:
            - .git/
        - action: rebuild
          path: ./internal
          target: ./app
        - action: rebuild
          path: ./proto
          target: ./app
  node:
    build:
      dockerfile: ./cmd/node/Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - MEMPOOL_API=mempool:8181
      - API_PORT=8080
    volumes:
      - ./data:/data
    develop:
      watch:
        - action: rebuild
          path: ./cmd/node
          target: ./app
          ignore:
            - .git/
        - action: rebuild
          path: ./internal
          target: ./app
        - action: rebuild
          path: ./proto
          target: ./app
  blocks:
    build:
      dockerfile: ./cmd/blocks/Dockerfile
      context: .
    ports:
      - "8282:8282"
    environment:
      - API_PORT=8282
    volumes:
      - ./data:/data
    develop:
      watch:
        - action: rebuild
          path: ./cmd/blocks
          target: ./app
          ignore:
            - .git/
        - action: rebuild
          path: ./internal
          target: ./app
        - action: rebuild
          path: ./proto
          target: ./app
  accounts:
    build:
      dockerfile: ./cmd/accounts/Dockerfile
      context: .
    ports:
      - "8383:8383"
    environment:
      - API_PORT=8383
    volumes:
      - ./data:/data
    develop:
      watch:
        - action: rebuild
          path: ./cmd/accounts
          target: ./app
          ignore:
            - .git/
        - action: rebuild
          path: ./internal
          target: ./app
        - action: rebuild
          path: ./proto
          target: ./app
