services:
  mempool:
    build:
      dockerfile: ./cmd/mempool/Dockerfile
      context: .
    ports:
      - "8181:8181"
    environment:
      - API_PORT=8181
      - DB_PATH=/data/mempool.db
    volumes:
      - ./cmd/mempool/data:/data
    develop:
      watch:
        - action: rebuild
          path: ./cmd/mempool
          target: ./app
          ignore:
            - .git/
            - data/
  node:
    build:
      dockerfile: ./cmd/node/Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - MEMPOOL_API=mempool:8181
      - STATE_API=state:8383
      - API_PORT=8080
    develop:
      watch:
        - action: rebuild
          path: ./cmd/node
          target: ./app
          ignore:
            - .git/
  state:
    build:
      dockerfile: ./cmd/state/Dockerfile
      context: .
    ports:
      - "8383:8383"
    environment:
      - API_PORT=8383
      - DB_PATH=/data/state.db
    volumes:
      - ./cmd/state/data:/data
    develop:
      watch:
        - action: rebuild
          path: ./cmd/state
          target: ./app
          ignore:
            - .git/
            - data/
  miner:
    build:
      dockerfile: ./cmd/miner/Dockerfile
      context: .
    environment:
      - MEMPOOL_API=mempool:8181
      - STATE_API=state:8383
    volumes:
      - ./cmd/miner/data:/data
    develop:
      watch:
        - action: rebuild
          path: ./cmd/miner
          target: ./app
          ignore:
            - .git/
            - data/
