# Builder stage
FROM golang:1.23-alpine AS builder

# Install protoc and required packages
RUN apk add --no-cache protobuf protobuf-dev git

# Install protoc-gen-go and protoc-gen-go-grpc
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31.0
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

WORKDIR /proto
ENTRYPOINT ["protoc"]
