// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: balancechange.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BalanceChangeService_CreateBalanceChange_FullMethodName = "/balancechange.BalanceChangeService/CreateBalanceChange"
)

// BalanceChangeServiceClient is the client API for BalanceChangeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BalanceChangeServiceClient interface {
	CreateBalanceChange(ctx context.Context, in *CreateBalanceChangeRequest, opts ...grpc.CallOption) (*CreateBalanceChangeResponse, error)
}

type balanceChangeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBalanceChangeServiceClient(cc grpc.ClientConnInterface) BalanceChangeServiceClient {
	return &balanceChangeServiceClient{cc}
}

func (c *balanceChangeServiceClient) CreateBalanceChange(ctx context.Context, in *CreateBalanceChangeRequest, opts ...grpc.CallOption) (*CreateBalanceChangeResponse, error) {
	out := new(CreateBalanceChangeResponse)
	err := c.cc.Invoke(ctx, BalanceChangeService_CreateBalanceChange_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceChangeServiceServer is the server API for BalanceChangeService service.
// All implementations must embed UnimplementedBalanceChangeServiceServer
// for forward compatibility
type BalanceChangeServiceServer interface {
	CreateBalanceChange(context.Context, *CreateBalanceChangeRequest) (*CreateBalanceChangeResponse, error)
	mustEmbedUnimplementedBalanceChangeServiceServer()
}

// UnimplementedBalanceChangeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBalanceChangeServiceServer struct {
}

func (UnimplementedBalanceChangeServiceServer) CreateBalanceChange(context.Context, *CreateBalanceChangeRequest) (*CreateBalanceChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBalanceChange not implemented")
}
func (UnimplementedBalanceChangeServiceServer) mustEmbedUnimplementedBalanceChangeServiceServer() {}

// UnsafeBalanceChangeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalanceChangeServiceServer will
// result in compilation errors.
type UnsafeBalanceChangeServiceServer interface {
	mustEmbedUnimplementedBalanceChangeServiceServer()
}

func RegisterBalanceChangeServiceServer(s grpc.ServiceRegistrar, srv BalanceChangeServiceServer) {
	s.RegisterService(&BalanceChangeService_ServiceDesc, srv)
}

func _BalanceChangeService_CreateBalanceChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBalanceChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceChangeServiceServer).CreateBalanceChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceChangeService_CreateBalanceChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceChangeServiceServer).CreateBalanceChange(ctx, req.(*CreateBalanceChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BalanceChangeService_ServiceDesc is the grpc.ServiceDesc for BalanceChangeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BalanceChangeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "balancechange.BalanceChangeService",
	HandlerType: (*BalanceChangeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBalanceChange",
			Handler:    _BalanceChangeService_CreateBalanceChange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "balancechange.proto",
}
