// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: config.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ConfigService_GetChainConfig_FullMethodName       = "/config.ConfigService/GetChainConfig"
	ConfigService_GetCurrentDifficulty_FullMethodName = "/config.ConfigService/GetCurrentDifficulty"
)

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigServiceClient interface {
	GetChainConfig(ctx context.Context, in *GetChainConfigRequest, opts ...grpc.CallOption) (*GetChainConfigResponse, error)
	GetCurrentDifficulty(ctx context.Context, in *GetCurrentDifficultyRequest, opts ...grpc.CallOption) (*GetCurrentDifficultyResponse, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) GetChainConfig(ctx context.Context, in *GetChainConfigRequest, opts ...grpc.CallOption) (*GetChainConfigResponse, error) {
	out := new(GetChainConfigResponse)
	err := c.cc.Invoke(ctx, ConfigService_GetChainConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetCurrentDifficulty(ctx context.Context, in *GetCurrentDifficultyRequest, opts ...grpc.CallOption) (*GetCurrentDifficultyResponse, error) {
	out := new(GetCurrentDifficultyResponse)
	err := c.cc.Invoke(ctx, ConfigService_GetCurrentDifficulty_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility
type ConfigServiceServer interface {
	GetChainConfig(context.Context, *GetChainConfigRequest) (*GetChainConfigResponse, error)
	GetCurrentDifficulty(context.Context, *GetCurrentDifficultyRequest) (*GetCurrentDifficultyResponse, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConfigServiceServer struct {
}

func (UnimplementedConfigServiceServer) GetChainConfig(context.Context, *GetChainConfigRequest) (*GetChainConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChainConfig not implemented")
}
func (UnimplementedConfigServiceServer) GetCurrentDifficulty(context.Context, *GetCurrentDifficultyRequest) (*GetCurrentDifficultyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentDifficulty not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_GetChainConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChainConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetChainConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetChainConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetChainConfig(ctx, req.(*GetChainConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetCurrentDifficulty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentDifficultyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetCurrentDifficulty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetCurrentDifficulty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetCurrentDifficulty(ctx, req.(*GetCurrentDifficultyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "config.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChainConfig",
			Handler:    _ConfigService_GetChainConfig_Handler,
		},
		{
			MethodName: "GetCurrentDifficulty",
			Handler:    _ConfigService_GetCurrentDifficulty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}
